fixed ad bug appearing even thouhg it shouldn't, now default to shown…
Magic-Fishes/Ecole-Directe-Plus-Unblock pull request #5
Opened 2024-09-10 21:01 UTC by Fefedu973

…, added close button, fixed big ad not appearing after login

2024-09-14 22:15 UTC, Truiteseche approved these changes

2024-09-21 00:19 UTC, Truiteseche requested changes

2024-09-21 00:19 UTC, Truiteseche commented on promoteEDP.js
> +}, 100);
Did you check the "hashchange" event for that ?

2024-09-21 14:48 UTC, Fefedu973 commented
c'est la seule méthode que j'ai trouvé qui fonctionne

2024-09-21 16:24 UTC, Truiteseche commented
no problem, thanks a lot for bug fix!

2024-09-21 16:24 UTC, merged